
import React, { useState } from 'react';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { CheckCircle, HelpCircle, Search } from 'lucide-react';
import { Input } from '@/components/ui/input';

const FAQPage = () => {
  const categories = [
    {
      name: 'General',
      faqs: [
        {
          question: 'What is Defection?',
          answer: 'Defection is a blockchain-powered platform that combines interactive storytelling with cryptocurrency incentives. Users can participate in daily scripts, develop characters, and earn rewards through active engagement with the platform\'s narrative ecosystem.'
        },
        {
          question: 'Do I need cryptocurrency to start?',
          answer: 'While you can browse and read some content without cryptocurrency, to fully participate in the Defection ecosystem and earn rewards, you\'ll need to connect a Web3 wallet. The platform supports various wallet providers including MetaMask, WalletConnect, and Coinbase Wallet.'
        },
        {
          question: 'Is Defection free to use?',
          answer: 'Defection operates on a freemium model. Basic features and daily scripts are available for free, but premium experiences, special character traits, and certain narrative branches may require DFC tokens or other forms of payment.'
        },
        {
          question: 'What blockchain does Defection use?',
          answer: 'Defection primarily operates on Ethereum and its Layer 2 solutions to balance security, decentralization, and transaction costs. We\'re also exploring multi-chain support to provide the best possible user experience.'
        }
      ]
    },
    {
      name: 'Scripts & Storytelling',
      faqs: [
        {
          question: 'How often are new scripts released?',
          answer: 'New daily scripts are released every 24 hours at 00:00 UTC. These scripts range from standalone experiences to episodes in ongoing narrative arcs that evolve based on community participation.'
        },
        {
          question: 'Can I contribute my own stories?',
          answer: 'Yes! Defection encourages community-created content. Writers can submit scripts through our Creator Portal, and approved submissions become part of our official library, with creators earning a share of the rewards generated by their content.'
        },
        {
          question: 'What happens if I miss a daily script?',
          answer: 'Daily scripts remain available for 72 hours after their initial release. After this period, they move to the archive, where they can still be experienced but may not offer the same level of rewards as current scripts.'
        },
        {
          question: 'How do my choices affect the narrative?',
          answer: 'Your choices in scripts can influence both the immediate story outcome and the broader narrative universe. Popular decisions across the community may become canonical, affecting future storylines and character development opportunities.'
        }
      ]
    },
    {
      name: 'Tokens & Rewards',
      faqs: [
        {
          question: 'What is the DFC token?',
          answer: 'DFC (Defection) is the native utility token of our ecosystem. It serves multiple purposes including governance voting, accessing premium content, character customization, and trading within our marketplace.'
        },
        {
          question: 'How do I earn DFC tokens?',
          answer: 'You can earn DFC tokens by completing daily scripts, participating in community challenges, contributing high-quality content, referring new users, and through special promotional events.'
        },
        {
          question: 'Where can I trade DFC tokens?',
          answer: 'DFC tokens are listed on several decentralized exchanges. Check our Tokenomics page for the most up-to-date information on trading pairs and liquidity pools.'
        },
        {
          question: 'Are rewards guaranteed?',
          answer: 'While participation generally leads to rewards, the specific amount may vary based on factors such as community engagement, quality of contribution, and scarcity mechanisms designed to maintain economic balance.'
        }
      ]
    },
    {
      name: 'Technical Support',
      faqs: [
        {
          question: 'My wallet won\'t connect. What should I do?',
          answer: 'First, ensure you\'re using a supported browser and wallet combination. Try refreshing the page, clearing your cache, or using a different browser. If problems persist, visit our Discord server for real-time support from our technical team.'
        },
        {
          question: 'I completed a script but didn\'t receive rewards.',
          answer: 'Rewards are typically processed within 10-15 minutes after script completion. If you haven\'t received your rewards after this time, check your wallet connection and transaction history. For unresolved issues, submit a support ticket with details of the script and approximate completion time.'
        },
        {
          question: 'How do I report a bug?',
          answer: 'Bugs can be reported through our GitHub repository or by submitting a detailed report via the "Help & Support" section in your account dashboard. Include steps to reproduce the issue, your browser/device information, and screenshots if possible.'
        },
        {
          question: 'Is my data secure?',
          answer: 'Defection prioritizes user privacy and data security. We utilize encryption protocols, secure authentication methods, and regular security audits to protect user information. For wallet-specific security, we recommend following best practices such as using hardware wallets and enabling two-factor authentication.'
        }
      ]
    }
  ];

  const [searchTerm, setSearchTerm] = useState('');
  const [activeCategory, setActiveCategory] = useState('General');

  // Filter FAQs based on search term
  const filteredCategories = searchTerm 
    ? categories.map(category => ({
        ...category,
        faqs: category.faqs.filter(faq => 
          faq.question.toLowerCase().includes(searchTerm.toLowerCase()) ||
          faq.answer.toLowerCase().includes(searchTerm.toLowerCase())
        )
      })).filter(category => category.faqs.length > 0)
    : categories;

  return (
    <div className="container mx-auto px-4 py-16 mt-16 min-h-screen">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-display font-bold mb-2 bg-clip-text text-transparent bg-gradient-to-r from-crypto-purple to-crypto-blue">
          Frequently Asked Questions
        </h1>
        <p className="text-foreground/70 mb-8">
          Find answers to common questions about the Defection platform
        </p>
        
        <div className="glass-card p-6 rounded-lg border border-white/10 mb-8">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-foreground/50" size={18} />
            <Input
              placeholder="Search for answers..."
              className="pl-10 bg-white/5 border-white/10 focus-visible:ring-crypto-purple/50"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
          
          {searchTerm && filteredCategories.length === 0 && (
            <div className="flex flex-col items-center justify-center p-8 text-center">
              <HelpCircle size={48} className="text-foreground/30 mb-4" />
              <h3 className="text-lg font-semibold mb-1">No results found</h3>
              <p className="text-foreground/60">
                We couldn't find any answers matching "{searchTerm}"
              </p>
              <button 
                className="mt-4 text-sm text-crypto-blue hover:underline"
                onClick={() => setSearchTerm('')}
              >
                Clear search
              </button>
            </div>
          )}
        </div>
        
        {!searchTerm && (
          <div className="flex overflow-x-auto mb-6 gap-3 pb-2 scrollbar-none">
            {categories.map((category) => (
              <button
                key={category.name}
                className={`px-4 py-2 rounded-full whitespace-nowrap transition-colors ${
                  activeCategory === category.name
                    ? 'bg-crypto-purple text-white'
                    : 'bg-white/5 hover:bg-white/10'
                }`}
                onClick={() => setActiveCategory(category.name)}
              >
                {category.name}
              </button>
            ))}
          </div>
        )}
        
        <div>
          {(searchTerm ? filteredCategories : categories.filter(c => c.name === activeCategory)).map((category) => (
            <div key={category.name} className="mb-8">
              {searchTerm && <h2 className="text-xl font-bold mb-4">{category.name}</h2>}
              
              <Accordion type="single" collapsible className="space-y-4">
                {category.faqs.map((faq, index) => (
                  <AccordionItem 
                    key={index} 
                    value={`${category.name}-${index}`}
                    className="border border-white/10 rounded-lg overflow-hidden bg-white/5"
                  >
                    <AccordionTrigger className="px-4 py-3 hover:bg-white/5 hover:no-underline font-medium data-[state=open]:text-crypto-blue">
                      {faq.question}
                    </AccordionTrigger>
                    <AccordionContent className="px-4 pb-4 pt-1 text-foreground/80">
                      {faq.answer}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </div>
          ))}
        </div>
        
        <div className="mt-12 p-6 rounded-lg border border-white/10 bg-gradient-to-br from-black/30 to-crypto-purple/10 text-center">
          <div className="flex justify-center mb-4">
            <CheckCircle size={32} className="text-crypto-purple" />
          </div>
          <h3 className="text-xl font-bold mb-2">Still have questions?</h3>
          <p className="text-foreground/70 mb-4">
            Our community and support team are here to help you with any other questions.
          </p>
          <div className="flex flex-wrap justify-center gap-4">
            <a href="#" className="px-4 py-2 bg-white/5 border border-white/10 rounded-lg hover:bg-white/10 transition-colors">
              Join Discord
            </a>
            <a href="#" className="px-4 py-2 bg-crypto-purple text-white rounded-lg hover:bg-crypto-purple/90 transition-colors">
              Contact Support
            </a>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FAQPage;
